### ISSUE TITLE
Can't download via composer

### ISSUE THREAD

**Issue by realmocaccino** [justbetter/laravel-pagination-with-havings#1]
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out

My internet connection is ok.

**Comment by royduin** [comment]
So it was your internet connection or where there troubles at packagist?

**Comment by realmocaccino** [comment]
There were troubles with packagist, but with all other packages as well.
But now it's fine.
By the way, I'm already using your package and it's working super well.
All paginations with having clause are now working, without affecting all
others.
Thank you!

Em Qua, 17 de out de 2018 17:29, Roy Duineveld <notifications@github.com>
escreveu:

**Comment by royduin** [comment]
Good to hear 😎
