### ISSUE TITLE
This package doesn't seem to support Laravel 5.8

### ISSUE THREAD

**Issue by wisnuvb** [justbetter/laravel-pagination-with-havings#2]
When I install an error like this appears:

`Problem 1
    - Installation request for justbetter/laravel-pagination-with-havings ^1.0 -> satisfiable by justbetter/laravel-pagination-with-havings[1.0].
    - Conclusion: remove laravel/framework v5.8.2
    - Conclusion: don't install laravel/framework v5.8.2
    - justbetter/laravel-pagination-with-havings 1.0 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.2].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.2].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.2].
    - Installation request for laravel/framework (locked at v5.8.2, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.2]`

**Comment by royduin** [comment]
Fixed in release 1.1 👍
