### ISSUE TITLE
newBaseQueryBuilder Error

### ISSUE THREAD

**Issue by naumanahmed19** [justbetter/laravel-pagination-with-havings#5]
Hi,

Thanks for this awesome package. It works great however there is a conflict with another package that I am using.
https://github.com/jarektkaczyk/eloquence

When I add trait I get the following error.
```
Trait method newBaseQueryBuilder has not been applied, because there are collisions with other trait methods
```

The following method fixes the problem but in that case, I cant use Sofa/Eloquence

```
    use PaginationWithHavings,Eloquence{
        PaginationWithHavings::newBaseQueryBuilder insteadof Eloquence;
    }
```

Any idea how to fix it?

**Comment by royduin** [comment]
You've to merge the functionality together on your own. Create your own builder class based on the builder from Eloquence (just extend that class) and overwrite the `runPaginationCountQuery()` method and merge the functionality together. After that overwrite the `newBaseQueryBuilder()` in the models and use your own Query Builder class. Or create a trait you can use.
